Migrate get evaluations query to Drizzle on API Frontend
lmnr-ai/lmnr pull request #160
Opened 2024-11-05 17:17 UTC by haikalvidya

closed https://github.com/lmnr-ai/lmnr/issues/81

2024-11-05 17:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/lmnr-ai/lmnr?pullRequest=160) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/lmnr-ai/lmnr?pullRequest=160) before we can accept your contribution.<br/><hr/>**Vidya Haikal** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/lmnr-ai/lmnr?pullRequest=160) it.</sub>

2024-11-05 21:47 UTC, dinmukhamedm reviewed
LGTM overall, though left small comments. Regarding the deletion you mentioned: it is fine to only delete the unused frontend code. If you feel like setting up rust and building app-server is a little too much, we will remove the redundant backend code ourselves

2024-11-05 21:47 UTC, dinmukhamedm commented on frontend/app/api/projects/[projectId]/evaluations/[evaluationId]/route.ts
> +    evaluation: evaluation[0],
Index out of bounds will cause a 500 error, I think we need to gracefully handle it here with a 404 or something.  As an option, you could re-write the query in a more ORM less SQL manner with drizzle's `query`, `findFirst`: https://orm.drizzle.team/docs/rqb#find-first but I am fine with select as well.

2024-11-05 21:47 UTC, dinmukhamedm commented on frontend/app/api/projects/[projectId]/evaluations/route.ts
> +    });
we've simplified paginated get a bit, sorry about that. If you could pull/merge the latest `dev` into your branch? It now looks like this:

```
  const result = await paginatedGet<any, Evaluation>({
    table: evaluations,
    filters: [eq(evaluations.projectId, projectId)],
    orderBy: desc(evaluations.createdAt),
  });
```

2024-11-05 21:47 UTC, dinmukhamedm commented on frontend/app/api/projects/[projectId]/evaluations/route.ts
> +  const groupId = searchParams.get('groupId');
nit. I'd suggest typing `req` as `NextRequest` and using `req.nextUrl.searchParams.get()` instead. I think it's just a bit more idiomatic and consistent with the rest of the code

2024-11-06 08:09 UTC, dinmukhamedm commented on frontend/app/api/projects/[projectId]/evaluations/[evaluationId]/route.ts
> +    );
I'm drafting another query for a different feature and I based it on this one you wrote. Your version will not run, because
1. cte alias in `$with` is identical to the column name inside it.
2. You need a `.with(subQueryScoreCte)`

See https://github.com/lmnr-ai/lmnr/pull/166 for an example where I finally made it work. Just letting you know :)

2024-11-06 08:24 UTC, dinmukhamedm commented on frontend/app/api/projects/[projectId]/evaluations/[evaluationId]/route.ts
> +    );
Ah, that also might be because we have a legacy column `scores` in the evaluations table. I will remove that soon, but for now, yes, you'll have to do something similar to what I did

2024-11-06 10:25 UTC, haikalvidya commented on frontend/app/api/projects/[projectId]/evaluations/[evaluationId]/route.ts
> +    );
aahh alright, will change that based on your query

2024-11-06 10:26 UTC, haikalvidya commented on frontend/app/api/projects/[projectId]/evaluations/route.ts
> +  const groupId = searchParams.get('groupId');
Ill change that for sure, to follow the idiomatic of codebase

2024-11-06 10:27 UTC, haikalvidya commented on frontend/app/api/projects/[projectId]/evaluations/[evaluationId]/route.ts
> +    evaluation: evaluation[0],
oh my bad not that carefully choose right method, I will change that using query then

2024-11-06 17:33 UTC, dinmukhamedm commented
Thanks @haikalvidya, amazing work! This looks good to me. Let me know once/if you've tested this

2024-11-09 08:47 UTC, haikalvidya commented
Hey @dinmukhamedm sorry for late response, I haven't been able to test the changes yet due to some reasons (I DM'ed you about it on discord). However, I think the code is ready for review.

2024-11-09 21:28 UTC, dinmukhamedm commented on frontend/app/project/[projectId]/evaluations/[evaluationId]/page.tsx
> +    `/api/projects/${params.projectId}/evaluations/${params.evaluationId}`
@haikalvidya sorry, hadn't realized  at first, but this will neither compile nor we should keep it here. Let's move the logic from the routes directly to this file (as util functions) and remove the API routes if they are unused. Also, please address the Ellipsis comment

2024-11-10 02:13 UTC, haikalvidya commented on frontend/app/project/[projectId]/evaluations/[evaluationId]/page.tsx
> +    `/api/projects/${params.projectId}/evaluations/${params.evaluationId}`
oohh, alright, will work on that today

2024-11-10 07:49 UTC, haikalvidya commented on frontend/app/project/[projectId]/evaluations/[evaluationId]/page.tsx
> +    `/api/projects/${params.projectId}/evaluations/${params.evaluationId}`
Could you kindly review my latest commit again?, i have tested the changes, and it is running well

2024-11-10 09:15 UTC, skull8888888 requested changes
qq: did you test everything locally?

2024-11-10 09:15 UTC, skull8888888 commented on frontend/app/project/[projectId]/evaluations/[evaluationId]/page.tsx
>    }
you can remove this (and its imports), middleware now protects all project/* and projects/* routes

2024-11-10 12:45 UTC, haikalvidya commented on frontend/app/project/[projectId]/evaluations/[evaluationId]/page.tsx
>    }
i have updated the code upon this matter

2024-11-10 19:00 UTC, dinmukhamedm approved these changes
Excellent work! Thanks!

2024-11-10 19:01 UTC, merged