frontend: expandable sidebar
lmnr-ai/lmnr pull request #273
Opened 2024-12-06 16:35 UTC by adilb99

A very hacky solution to having an expandable sidebar, but it works well on local so far. To do:

- [ ] maybe a more robust check for whether it's a project page or a root page @ frontend/components/ui/header.tsx:26-28 (or use a different header component in the project page to have the SidebarTrigger properly in the header without affecting the root layout page).

- [ ] less hacky styling cause currently the sidebar.tsx uses some of the styles from the old navbar directly instead of a reusable way.

- [ ] merge conflicts?

2024-12-06 16:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/lmnr-ai/lmnr?pullRequest=273) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/lmnr-ai/lmnr?pullRequest=273) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: skull8888888<br/>:x: adilb99<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/lmnr-ai/lmnr?pullRequest=273) it.</sub>

2024-12-06 16:54 UTC, dinmukhamedm reviewed
LGTM overall, left a few nitpicks, and there is clearly some more work to do

2024-12-06 16:54 UTC, dinmukhamedm commented on frontend/app/globals.css
> +    --sidebar-ring: 217.2 91.2% 59.8%;
are all these additional colors required by shadcn's `<Sidebar>`. Otherwise, I don't think we need them all, and could just tailwind all the necessary colors on the sidebar

2024-12-06 16:54 UTC, dinmukhamedm commented on frontend/assets/logo/laminar.svg
we'll add the new logo anw I guess

2024-12-06 16:54 UTC, dinmukhamedm commented on frontend/components/project/project-navbar.tsx
> +      <SidebarHeader className="h-14 bg-background">
I'd say we center this: `mx-auto`? But again, let's wait for Robert's input

2024-12-06 16:54 UTC, dinmukhamedm commented on frontend/components/project/project-navbar.tsx
> +          <AvatarMenu />
avatar in the corner of an expanded sidebar looks a bit too empty. Should we maybe add an email to the right of it?

2024-12-06 16:54 UTC, dinmukhamedm commented on frontend/components/ui/sidebar.tsx
> +            document.cookie = `${SIDEBAR_COOKIE_NAME}=${openState}; path=/; max-age=${SIDEBAR_COOKIE_MAX_AGE}`;
Good one, but this is auto-downloaded from shadcn

2024-12-06 16:54 UTC, dinmukhamedm commented on frontend/tailwind.config.js
ouch, what's up with indents here?

2024-12-06 17:18 UTC, adilb99 commented on frontend/app/globals.css
> +    --sidebar-ring: 217.2 91.2% 59.8%;
@dinmukhamedm that's one of my todos actually. These were the colors originally brought over from shadcn, but I ended up using the existing ones defined for the old navbar. So, we could either remove these or put them back into the classNames and tweak to be similar to the old navbar. The pros of the latter is we can decouple those colors from the navbar since they are also used elsewhere afaik (i.e. bg-primary, bg-secondary, etc.)

2024-12-06 17:28 UTC, dinmukhamedm commented on frontend/app/globals.css
> +    --sidebar-ring: 217.2 91.2% 59.8%;
@adilb99 Ah I see, you're saying we've already had these colors defined somewhere? Yeah, let's do classNames that we already have

2024-12-06 18:51 UTC, skull8888888 requested changes

2024-12-06 18:51 UTC, skull8888888 commented on frontend/assets/logo/laminar.svg
we already have new logo, check out how we do it in projects header and on landing header

2024-12-06 18:51 UTC, skull8888888 commented on frontend/assets/logo/laminar.svg
so we should remove the old one

2024-12-06 18:51 UTC, skull8888888 commented on frontend/components/ui/header.tsx
> +        {projectId.length > 0 && (
just add a prop, something like showSidebarButton and default to true, on /projects set it to false.

2024-12-06 18:51 UTC, skull8888888 commented on frontend/components/project/project-navbar.tsx
> +          <AvatarMenu />
name and email underneath.

2024-12-06 18:51 UTC, skull8888888 commented on frontend/components/project/project-navbar.tsx
>  import {
sidebar is too large, lots of empty space on the right to the text, let's make it smaller, around to the size of the largest text

2024-12-07 07:58 UTC, adilb99 commented
Addressed the comments. Gist:

- Better props in the header and avatar components
- Added email to the right of the avatar picture when expanded (username omitted due to being same as email)
- Narrower sidebar when expanded, aligned with the email
- Using new logo on expanded, deleted the old logo file + better naming for imported logos
- Decided to keep the sidebar css classes due to most of them still being used by sidebar.tsx

Let me know if there are any more improvements to be made. Otherwise, should be good to go!

2024-12-07 08:44 UTC, skull8888888 commented
Looks good, few things.
- State of the sidebar should be saved. Seems like sidebar should already have this kind of functionality judging by the fact that it has some cookies stuff. If it doesn't let's just use localStorage
- padding on the avatar should be consistent with the rest of the sidebar, seems like sidebar has p-4 but avatar p-2?
<img width="223" alt="Screenshot 2024-12-07 at 12 37 16 AM" src="https://github.com/user-attachments/assets/d87e36bf-2640-4a14-bb90-4f41d57dc8bb">

- let's actually make max width of the sidebar to the width of the largest option, in this case it's playgrounds. Let's truncate email. Because aligning max size with email would cause sidebar to be very large if a user has a very long email.
- button should align with the rest of the content which has p-4. Align button so that it aligns with the rest of the content.
<img width="464" alt="Screenshot 2024-12-07 at 12 42 26 AM" src="https://github.com/user-attachments/assets/3b2103f0-37b5-495a-96b4-4e66722b8073">

In general look at inconsistencies in the alignment, they immediately strike eyes.

2024-12-07 10:45 UTC, adilb99 commented
Fixed the following:

- Smaller sidebar width closer aligned with Playgrounds menu item
- Fixed padding and alignment issues
- Sidebar state is saved in the cookies and properly used. (see the next comment for details)

2024-12-07 10:49 UTC, adilb99 commented on frontend/components/ui/sidebar.tsx
> +        }, [setOpenProp]); // Only runs once on mount
This is needed to handle SSR properly and not use `document` var before it is populated. However, this produces a slight lag when applying sidebar state on reload. Same occurs with proper usage of localStorage.

Possible solution is to retrieve the cookies on the server-side in layout.tsx and passing it into the component as a prop, but then propagating it back server-side to properly save makes the code a little too complex.

Possibly not a problem cause local frontend is a little slow and won't be so visible in production environment, but let me know your thoughts. @skull8888888 @dinmukhamedm

2024-12-08 07:11 UTC, dinmukhamedm commented on frontend/tailwind.config.js
> +  	container: {
looks like indents are messed up again

2024-12-08 07:18 UTC, dinmukhamedm reviewed
LGTM. Not explicitly approving as @skull8888888 has this checked out, so he'll have another look before we merge

2024-12-08 07:41 UTC, skull8888888 requested changes
last change, otherwise lgtm

2024-12-08 07:41 UTC, skull8888888 commented on frontend/tailwind.config.js
> -        'lg': ['1.125rem', { lineHeight: '1.6rem', letterSpacing: '-0.0125em' }],
bring 'lg' and 'xl' back and put them in comas for consistency

2024-12-08 08:17 UTC, merged