feat: add items count column to datasets list
lmnr-ai/lmnr pull request #276
Opened 2024-12-08 10:12 UTC by raj921

- Added SQL query to count datapoints per dataset
- Added items count to dataset API response
- Added Items column to datasets table in UI

2024-12-08 10:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/lmnr-ai/lmnr?pullRequest=276) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/lmnr-ai/lmnr?pullRequest=276) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/lmnr-ai/lmnr?pullRequest=276) it.</sub>

2024-12-08 16:17 UTC, raj921 commented on app-server/src/routes/datasets.rs
> +#[get("datasets")]
done it

2024-12-18 21:18 UTC, dinmukhamedm requested changes
Hey @raj921! Thanks for your PR! This looks good, but I think we actually fetch datasets from the frontend using drizzle, so there was no need to alter this in app-server. You should probably modify https://github.com/lmnr-ai/lmnr/blob/main/frontend/app/api/projects/%5BprojectId%5D/datasets/route.ts#L34 instead

2024-12-26 18:44 UTC, closed without merging

2024-12-26 18:44 UTC, dinmukhamedm commented
Closing in favour of #288